### ISSUE TITLE
State Channel v3 phase 1

### ISSUE THREAD

**Issue by jdgemm** [helium/router#525]
Phase 1 (blueprints, foundation)
State channel - decouple from core, create own library
Sequence diagrams; new protos, protocols

**Comment by macpie** [comment]
- [ ] Use ETS / basic counter to represent state channel balances

**Comment by macpie** [comment]
### TODOS

@michaeldjeffrey 

- [ ] ReadMe: basic explanation of what is a SC and why we need to use it
- [ ] Diagram top (level) to bottom
- [ ] Proto file review

@macpie 

- [ ] Create repo
- [ ]  Reconcile data exchange in session based SC, how can SC knows hos much data was passed around?
